runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  
- url: /index\.html
  script: index.php
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
  
- url: /(.*\.(gif|png|jpg))$
  static_files: \1
  upload: (.*\.(gif|png|jpg))$
  application_readable: true

- url: /.*
  script: not_found.php